---

- name: Install postfix
  openbsd_pkg:
    name: "{{ postfix_package }}"
    state: present

- name: Install postfix_extra_packages
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items: "{{ postfix_extra_packages }}"

- name: Create /etc/mailer.conf
  command: /usr/local/sbin/postfix-enable
  args:
    creates: /etc/mailer.conf.pre-postfix

- name: Stop smtpd
  service:
    name: smtpd
    state: stopped
    enabled: false

- name: Enable postfix
  service:
    name: "{{ postfix_service }}"
    enabled: yes
