---

- name: Install gmake
  yum:
    name: make
    state: present

- name: Install postfix
  yum:
    name: "{{ postfix_package }}"
    state: present

- name: Enable postfix
  service:
    name: "{{ postfix_service }}"
    enabled: yes
